# Generated by Django 4.2.8 on 2025-12-19 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerassignment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_assignments', to='core.application'),
        ),
        migrations.AlterField(
            model_name='officerassignment',
            name='officer',
            field=models.ForeignKey(limit_choices_to={'role': 'officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
