# Generated by Django 4.2.8 on 2025-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_poll_polloption_loginhistory_familymember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizendocumentlocker',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
