# Generated by Django 4.2.8 on 2025-12-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
