# Generated by Django 4.2.8 on 2026-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_department_latitude_department_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievanceticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='grievance_attachments/'),
        ),
        migrations.AddField(
            model_name='grievanceticket',
            name='category',
            field=models.CharField(choices=[('sanitation', 'Sanitation'), ('electricity', 'Electricity'), ('water', 'Water Supply'), ('road', 'Road Maintenance'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
