# Generated by Django 4.2.8 on 2026-01-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_grievanceticket_attachment_grievanceticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('news', 'News & Updates'), ('circular', 'Circular & Notice'), ('alert', 'Emergency Alert'), ('deadline', 'Deadline & Reminder'), ('tender', 'Tender'), ('policy', 'Policy Update')], default='news', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High / Critical')], default='normal', max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('document', models.FileField(blank=True, help_text='PDF or Document for download', null=True, upload_to='announcements/docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
