# Generated by Django 4.2.8 on 2026-01-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='eGovernance Portal', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registration', models.BooleanField(default=True)),
                ('global_alert_message', models.TextField(blank=True, help_text='Message to display on top of all pages', null=True)),
                ('contact_email', models.EmailField(default='admin@egov.com', max_length=254)),
                ('contact_phone', models.CharField(default='1800-123-4567', max_length=20)),
            ],
        ),
    ]
