# Generated by Django 4.2.8 on 2026-01-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
