# Generated by Django 4.2.8 on 2026-01-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('prod', 'Production')], default='dev', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('portal_name', models.CharField(default='e-Governance Portal', max_length=100)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('max_upload_size_mb', models.IntegerField(default=5)),
                ('global_sla_days', models.IntegerField(default=7)),
                ('enable_grievances', models.BooleanField(default=True)),
                ('enable_appointments', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
