# Generated by Django 4.2.8 on 2026-01-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(blank=True, help_text='Specific role to target (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('news', 'News & Updates'), ('circular', 'Circular & Notice'), ('alert', 'Emergency Alert'), ('broadcast', 'Emergency Broadcast Mode'), ('policy', 'Policy Update'), ('internal', 'Internal Memo (Staff Only)')], default='news', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High / Critical'), ('emergency', 'Life-Safety / Immediate')], default='normal', max_length=15),
        ),
    ]
