# Generated by Django 4.2.8 on 2026-01-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_announcement_target_role_alter_announcement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='maintenance_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='system_version',
            field=models.CharField(default='2.4.0-build.82', max_length=20),
        ),
    ]
