# Generated by Django 4.2.8 on 2026-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_systemconfiguration_maintenance_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('priority', 'Priority')], default='normal', max_length=10),
        ),
    ]
